//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public class photoeditEntities : DbContext, IPhotoeditEntities
    {
        public photoeditEntities() : base("name=photoeditEntities")
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Abonamente> Abonamente { get; set; }
        public virtual DbSet<Edits> Edits { get; set; }
        public DbSet<Fotografii> Fotografii { get; set; }
        public virtual DbSet<Utilizatori> Utilizatori { get; set; }

    }
}
