//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizatori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizatori()
        {
            this.Edits = new HashSet<Edits>();
            this.Fotografii = new HashSet<Fotografii>();
        }
    
        public int id { get; set; }
        public string nume { get; set; }
        public string email { get; set; }
        public string parola { get; set; }
        public System.DateTime data_inregistrare { get; set; }
        public Nullable<int> abonament_id { get; set; }
        public int rol { get; set; }
        public Nullable<int> campnou { get; set; }
    
        public virtual Abonamente Abonamente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edits> Edits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotografii> Fotografii { get; set; }
    }
}
